### ISSUE TITLE
Location on server of webpage push

### ISSUE THREAD

**Issue by pbitzer** [project-mjolnir/sindri#11]
Right now, the location on the server of where the webpages are pushed is in `src/website/mjolnir-website.lektorproject`, and this is in version control. This value needs to be different for each sensor, so we need to find a way to have a way to specify the location differently for each sensor site.

**Comment by CAM-Gerlach** [comment]
Yep, fully decoupling the config from the code is the main thing in work for v0,3.0. In particular, `website.py` and the lektorproject will be configurable outside of the code, falling back to the current defaults if anything isn't specified. It'll use Brokkr's existing config management system, so you can set most things at the system level and then any unit-specific overrides on the device, and I'd add a small feature that will autofill the unit name and number in standard placeholders in the `lektorproject` so it should be usable out of the box with no additional per-unit config. This will also be needed for the Sindri instance running on the VPS.

**Comment by CAM-Gerlach** [comment]
Fixed in deployed v0.3.0a1 with the config being pulled out to `mjolnir-hamma` and automatically pushing to the correct subdir determined by the Brokkr unit number; PR incoming. In v0.3.0a2, Sindri won't need to run on the Pis at all, just once on the server.

**Comment by CAM-Gerlach** [comment]
Resolved by #18
