### ISSUE TITLE
General color coding improvements of website

### ISSUE THREAD

**Issue by pbitzer** [project-mjolnir/sindri#2]
Update the color scheme of a few of the variables display on the website. 

Some of these is probably specific to our use case, so at some point these values may need to be broken out to a config file, etc.

**Comment by CAM-Gerlach** [comment]
> Some of these is probably specific to our use case, so at some point these values may need to be broken out to a config file, etc.

Yeah, Sindri 0.3.0 will have a simplified declarative config file that can go in `mjolnir-hamma` instead of just a de-facto conf.py as part of the source tree, which will include the color coding, while some of the lower-level stuff here will go in higher-level functions/presets in the source.

**Comment by CAM-Gerlach** [comment]
If you already did this locally want to drop a PR with your changes for v0.2.9 (perhaps combined with #3 if that's easier for you), feel free, I can prioritize fast-track reviewing and merging.

**Comment by CAM-Gerlach** [comment]
Seems like this was fixed a long time ago by #12
