### ISSUE TITLE
Change default layout of website

### ISSUE THREAD

**Issue by pbitzer** [project-mjolnir/sindri#3]
Typical use has given us an idea of what the default layout should. More important blocks should go higher up, logged values that have little variation don't need to be plotted, etc.

**Comment by CAM-Gerlach** [comment]
I believe you've already done this locally, right? Want to get this in for `v0.2.9`?

**Comment by CAM-Gerlach** [comment]
Now that #10 is merged, can we consider this resolved @pbitzer ?
